### ISSUE TITLE
Add link from plugin page to this repo 

### ISSUE THREAD

**Issue by Alexsey** [andreycizov/idea-partialnav#4]
There should be a links to this repo on the [JetBrains plugin page](https://plugins.jetbrains.com/plugin/11952-partial-navigation)

Like on this [plugin page](https://plugins.jetbrains.com/plugin/8097-js-graphql/), labels **<> Source Code** and **Issue Tracker**

It will help to find the issue tracker, increases chances that someone would make a PR and add stars :)

**Comment by andreycizov** [comment]
Done!
